In [1]:
import pandas as pd
import os
import re

In [12]:
#Function that cleans the scraping data and builds/exports the final dataframe
us_zip_df = pd.read_csv('../../../Resources/Data/simplemaps_uszips_basicv1.80/uszips.csv', dtype={'zip':str, 'count_fips':'str'})
us_zip_df

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
0,00601,18.18027,-66.75266,Adjuntas,PR,Puerto Rico,True,NaN,16773.0,100.5,72001,Adjuntas,"{""72001"": 98.76, ""72141"": 1.24}",Adjuntas|Utuado,72001|72141,False,False,America/Puerto_Rico
1,00602,18.36075,-67.17541,Aguada,PR,Puerto Rico,True,NaN,37083.0,472.1,72003,Aguada,"{""72003"": 100}",Aguada,72003,False,False,America/Puerto_Rico
2,00603,18.45744,-67.12225,Aguadilla,PR,Puerto Rico,True,NaN,45652.0,513.2,72005,Aguadilla,"{""72005"": 99.76, ""72099"": 0.24}",Aguadilla|Moca,72005|72099,False,False,America/Puerto_Rico
3,00606,18.16585,-66.93716,Maricao,PR,Puerto Rico,True,NaN,6231.0,54.3,72093,Maricao,"{""72093"": 82.28, ""72153"": 11.67, ""72121"": 6.05}",Maricao|Yauco|Sabana Grande,72093|72153|72121,False,False,America/Puerto_Rico
4,00610,18.29110,-67.12243,Anasco,PR,Puerto Rico,True,NaN,26502.0,275.7,72011,Añasco,"{""72011"": 96.71, ""72099"": 2.81, ""72083"": 0.37,...",Añasco|Moca|Las Marías|Aguada,72011|72099|72083|72003,False,False,America/Puerto_Rico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33783,99923,55.98043,-130.03803,Hyder,AK,Alaska,True,NaN,12.0,0.3,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,02198,False,False,America/Sitka
33784,99925,55.55398,-132.96276,Klawock,AK,Alaska,True,NaN,990.0,7.1,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,02198,False,False,America/Sitka
33785,99926,55.12617,-131.48928,Metlakatla,AK,Alaska,True,NaN,1582.0,4.6,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,02198,False,False,America/Metlakatla
33786,99927,56.33305,-133.60044,Point Baker,AK,Alaska,True,NaN,0.0,0.0,2198,Prince of Wales-Hyder,"{""02198"": 100}",Prince of Wales-Hyder,02198,False,False,America/Sitka
33787,99929,56.36089,-132.00635,Wrangell,AK,Alaska,True,NaN,2509.0,0.4,2275,Wrangell,"{""02275"": 100}",Wrangell,02275,False,False,America/Sitka

In [15]:
zips_df = us_zip_df[us_zip_df.state_id == 'AR']
zips_df

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
25080,71601,34.17409,-91.89811,Pine Bluff,AR,Arkansas,True,NaN,14119.0,47.3,5069,Jefferson,"{""05069"": 99.53, ""05079"": 0.47}",Jefferson|Lincoln,05069|05079,False,False,America/Chicago
25081,71602,34.27463,-92.13302,White Hall,AR,Arkansas,True,NaN,15642.0,46.1,5069,Jefferson,"{""05069"": 83.32, ""05053"": 16.68}",Jefferson|Grant,05069|05053,False,False,America/Chicago
25082,71603,34.12881,-92.08492,Pine Bluff,AR,Arkansas,True,NaN,30791.0,70.8,5069,Jefferson,"{""05069"": 84.6, ""05079"": 7.69, ""05025"": 5.23, ...",Jefferson|Lincoln|Cleveland|Grant,05069|05079|05025|05053,False,False,America/Chicago
25083,71630,33.61827,-91.23004,Arkansas City,AR,Arkansas,True,NaN,513.0,8.4,5041,Desha,"{""05041"": 100}",Desha,05041,False,False,America/Chicago
25084,71631,33.58205,-92.26415,Banks,AR,Arkansas,True,NaN,547.0,1.7,5011,Bradley,"{""05011"": 100}",Bradley,05011,False,False,America/Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25690,72952,35.56861,-94.30139,Rudy,AR,Arkansas,True,NaN,2138.0,16.9,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago
25691,72955,35.60810,-94.44445,Uniontown,AR,Arkansas,True,NaN,778.0,21.7,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago
25692,72956,35.46895,-94.34890,Van Buren,AR,Arkansas,True,NaN,36726.0,136.7,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago
25693,72958,34.90173,-94.14659,Waldron,AR,Arkansas,True,NaN,6762.0,8.0,5127,Scott,"{""05127"": 100}",Scott,05127,False,False,America/Chicago
25694,72959,35.77157,-94.06686,Winslow,AR,Arkansas,True,NaN,3030.0,5.8,5143,Washington,"{""05143"": 59.17, ""05033"": 25.37, ""05047"": 15.46}",Washington|Crawford|Franklin,05143|05033|05047,False,False,America/Chicago

In [21]:
zips_df['county_fips_edit'] = zips_df['county_fips'].apply('{:0>5}'.format)
zips_df

C:\Users\jonat\AppData\Local\Temp\ipykernel_5136\3141627945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zips_df['county_fips_edit'] = zips_df['county_fips'].apply('{:0>5}'.format)

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone,county_fips_edit
25080,71601,34.17409,-91.89811,Pine Bluff,AR,Arkansas,True,NaN,14119.0,47.3,5069,Jefferson,"{""05069"": 99.53, ""05079"": 0.47}",Jefferson|Lincoln,05069|05079,False,False,America/Chicago,05069
25081,71602,34.27463,-92.13302,White Hall,AR,Arkansas,True,NaN,15642.0,46.1,5069,Jefferson,"{""05069"": 83.32, ""05053"": 16.68}",Jefferson|Grant,05069|05053,False,False,America/Chicago,05069
25082,71603,34.12881,-92.08492,Pine Bluff,AR,Arkansas,True,NaN,30791.0,70.8,5069,Jefferson,"{""05069"": 84.6, ""05079"": 7.69, ""05025"": 5.23, ...",Jefferson|Lincoln|Cleveland|Grant,05069|05079|05025|05053,False,False,America/Chicago,05069
25083,71630,33.61827,-91.23004,Arkansas City,AR,Arkansas,True,NaN,513.0,8.4,5041,Desha,"{""05041"": 100}",Desha,05041,False,False,America/Chicago,05041
25084,71631,33.58205,-92.26415,Banks,AR,Arkansas,True,NaN,547.0,1.7,5011,Bradley,"{""05011"": 100}",Bradley,05011,False,False,America/Chicago,05011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25690,72952,35.56861,-94.30139,Rudy,AR,Arkansas,True,NaN,2138.0,16.9,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago,05033
25691,72955,35.60810,-94.44445,Uniontown,AR,Arkansas,True,NaN,778.0,21.7,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago,05033
25692,72956,35.46895,-94.34890,Van Buren,AR,Arkansas,True,NaN,36726.0,136.7,5033,Crawford,"{""05033"": 100}",Crawford,05033,False,False,America/Chicago,05033
25693,72958,34.90173,-94.14659,Waldron,AR,Arkansas,True,NaN,6762.0,8.0,5127,Scott,"{""05127"": 100}",Scott,05127,False,False,America/Chicago,05127
25694,72959,35.77157,-94.06686,Winslow,AR,Arkansas,True,NaN,3030.0,5.8,5143,Washington,"{""05143"": 59.17, ""05033"": 25.37, ""05047"": 15.46}",Washington|Crawford|Franklin,05143|05033|05047,False,False,America/Chicago,05143

In [4]:
zips_df.dtypes

zip                  object
lat                 float64
lng                 float64
city                 object
state_id             object
state_name           object
zcta                   bool
parent_zcta         float64
population          float64
density             float64
county_fips           int64
county_name          object
county_weights       object
county_names_all     object
county_fips_all      object
imprecise              bool
military               bool
timezone             object
dtype: object

In [22]:
# Contaminant scraped data
EWG_Scrape_df = pd.read_csv(os.path.join(state_dir, 'contaminants.csv'), on_bad_lines='skip')
df = EWG_Scrape_df.copy()

In [23]:
#Dataframe for utilities zip info
utils_zip_df = pd.read_csv(os.path.join(state_dir, 'utilities.csv'), on_bad_lines='skip')
df2 = utils_zip_df.copy()
df2 = df2.rename(columns={'Utility name':'Utility'})

In [24]:
#Assign a unique primary key to each utility
df2['key'] = pd.factorize(df2['Utility'])[0]
# Create a dictionay to map the primary key to the contaminants df    
key_dict = df2.set_index('Utility').to_dict()['key']

In [25]:
#Map the primary key to Contaminants df and reassign the datatype as int
df['key'] = df['Utility'].map(key_dict)
df['key'] = pd.Series(df['key'],dtype=pd.Int64Dtype())

In [26]:
#Set the index of the dataframes to the primary key
df = df.set_index('key')
df2 = df2.set_index('key')

In [27]:
#Do a left join on the primary key
df3 = df.join(df2, lsuffix='_caller', rsuffix='_other')

In [28]:
#Drop rows that have the NaN values that are present in rsuffix column
df3 = df3.dropna(subset=['Utility_other'])

In [29]:
#Drop rows with non EWG Guideline for a contaminant
df3.dropna(subset=['EWG HEALTH GUIDELINE'], inplace=True)

In [30]:
#Split of the contaminant measurements and units and people served
df3['Units'] = df3['Utility Measuremnt'].apply(lambda x: x.split()[-1])
df3['Utility Measuremnt'] = df3['Utility Measuremnt'].apply(lambda x: x.split()[0])
df3['EWG HEALTH GUIDELINE'] = df3['EWG HEALTH GUIDELINE'].apply(lambda x: x.split()[0])
df3['Legal Limit']=df3['Legal Limit'].apply(lambda x: '0 units' if pd.isnull(x) else x)
df3['Legal Limit'] = df3['Legal Limit'].apply(lambda x: x.split()[0])
df3['People served'] = df3['People served'].apply(lambda x: x.split(':')[-1])

In [31]:
#Add a column for the state
df3['State'] = state_dir

In [32]:
#Replace any commas in the thousandths place
df3.replace(',','', regex=True, inplace=True)

In [33]:
#Change the datatype of the measurements and EWG Guidlines to numeric values
df3['Utility Measuremnt'] = pd.to_numeric(df3['Utility Measuremnt'])
df3['EWG HEALTH GUIDELINE'] = pd.to_numeric(df3['EWG HEALTH GUIDELINE'])
df3['People served'] = pd.to_numeric(df3['People served'])

In [34]:
#Define the Contaminant Factor (how many times larger is the utility measurement than EWG guideline)
df3['Contaminant_Factor'] = df3['Utility Measuremnt']/df3['EWG HEALTH GUIDELINE']

In [35]:
#Rename the column and drop the redundant 'Utility_other' column
df3 = df3.rename(columns={'Utility_caller':'Utility'})
df3 = df3.drop(columns=['Utility_other'])

In [36]:
#Reorder Columns
df3 = df3.reindex(columns=['State', 'City', 'Zip', 'Utility', 'People served', 'Contaminant', 'Utility Measuremnt', 'EWG HEALTH GUIDELINE',
   'Legal Limit', 'Units', 'Contaminant_Factor'])

In [37]:
#Write cleaned dataset to state directory
df3.to_csv(os.path.join(state_dir,'contaminants_cleaned.csv'), index=False)

In [46]:
#Make a unique list of the Utilities to loop through next
utlities_list = list(df3.Utility.unique())

# Loop through the contaminants df, select a subset for each utility, calculate the sum of the contaminant factor
# And generate a dictionary value for these data to be used in final dataset df
new_dataset = []
for utility in utlities_list:
    temp_df = df3[df3.Utility == utility]
    cont_factor_sum = round(temp_df.Contaminant_Factor.sum())
    zipcode = temp_df['Zip'].values[0]
    state = temp_df['State'].values[0]
    pop_served = temp_df['People served'].values[0]
    #print(f'The Contaminant factor for {utility} is: {cont_factor_sum}')
    new_dataset_dict = {
        'State': state,
        'Zip' : zipcode,
        'Utility' : utility,
        'Population Served': pop_served,
        'Contaminant_Factor' : cont_factor_sum

    }
    new_dataset.append(new_dataset_dict)

new_dataset_df = pd.DataFrame(new_dataset)
new_dataset_df.Zip = new_dataset_df.Zip.astype('int')

In [54]:
new_dataset_df.Zip = new_dataset_df.Zip.astype('str')
new_dataset_df

,State,Zip,Utility,Population Served,Contaminant_Factor,county_FIPS
0,AR,71601,Arkansas Department of Corrections - Cummins U...,3800,379,NaN
1,AR,71601,Arsenal Water,2577,255,NaN
2,AR,71601,Garrett Bridge Water Association,784,75,NaN
3,AR,71601,Gould Municipal,908,28,NaN
4,AR,71601,Grady Waterworks,424,152,NaN
...,...,...,...,...,...,...
92,AR,72826,Blue Mountain,357,1143,NaN
93,AR,72826,Subiaco City,535,1263,NaN
94,AR,72901,Franklin-Sebatian Public Water Authority,0,1013,NaN
95,AR,72901,James Fork Regional Water District,11538,1311,NaN
96,AR,72901,Milltown-washburn,3807,1163,NaN

In [55]:
# Create a dictionary to map the zip codes for each utility to the respective county FIPS code
c_FIPS_dict = zips_df.set_index('zip').to_dict()['county_fips_edit']
c_FIPS_dict

{'71601': '05069',
 '71602': '05069',
 '71603': '05069',
 '71630': '05041',
 '71631': '05011',
 '71635': '05003',
 '71638': '05043',
 '71639': '05079',
 '71640': '05017',
 '71642': '05003',
 '71643': '05079',
 '71644': '05079',
 '71646': '05003',
 '71647': '05011',
 '71651': '05011',
 '71652': '05025',
 '71653': '05017',
 '71654': '05041',
 '71655': '05043',
 '71658': '05003',
 '71659': '05069',
 '71660': '05025',
 '71661': '05003',
 '71662': '05041',
 '71663': '05017',
 '71665': '05025',
 '71666': '05041',
 '71667': '05079',
 '71670': '05041',
 '71671': '05011',
 '71674': '05041',
 '71675': '05043',
 '71676': '05003',
 '71677': '05043',
 '71678': '05079',
 '71701': '05103',
 '71720': '05103',
 '71721': '05019',
 '71722': '05099',
 '71724': '05139',
 '71725': '05039',
 '71726': '05103',
 '71728': '05019',
 '71730': '05139',
 '71740': '05027',
 '71742': '05039',
 '71743': '05019',
 '71744': '05013',
 '71745': '05013',
 '71747': '05139',
 '71748': '05039',
 '71749': '05139',
 '71751': '05103',
 '71752': '05027',
 '71753': '05027',
 '71758': '05139',
 '71759': '05139',
 '71762': '05139',
 '71763': '05039',
 '71764': '05103',
 '71765': '05139',
 '71766': '05013',
 '71770': '05027',
 '71772': '05019',
 '71801': '05057',
 '71820': '05081',
 '71822': '05081',
 '71823': '05133',
 '71825': '05057',
 '71826': '05073',
 '71827': '05073',
 '71831': '05061',
 '71832': '05133',
 '71833': '05061',
 '71834': '05091',
 '71835': '05099',
 '71836': '05081',
 '71837': '05091',
 '71838': '05057',
 '71839': '05091',
 '71841': '05133',
 '71842': '05133',
 '71845': '05073',
 '71846': '05133',
 '71847': '05057',
 '71851': '05061',
 '71852': '05061',
 '71853': '05081',
 '71854': '05091',
 '71855': '05057',
 '71857': '05099',
 '71858': '05099',
 '71859': '05057',
 '71860': '05073',
 '71861': '05073',
 '71862': '05057',
 '71864': '05099',
 '71865': '05081',
 '71866': '05081',
 '71901': '05051',
 '71909': '05051',
 '71913': '05051',
 '71921': '05019',
 '71922': '05109',
 '71923': '05019',
 '71929': '05059',
 '71933': '05051',
 '71935': '05097',
 '71937': '05113',
 '71940': '05109',
 '71941': '05059',
 '71942': '05059',
 '71943': '05109',
 '71944': '05113',
 '71945': '05113',
 '71949': '05051',
 '71950': '05109',
 '71952': '05109',
 '71953': '05113',
 '71956': '05051',
 '71957': '05097',
 '71958': '05109',
 '71959': '05109',
 '71960': '05097',
 '71961': '05097',
 '71962': '05019',
 '71964': '05051',
 '71965': '05097',
 '71968': '05051',
 '71969': '05097',
 '71970': '05097',
 '71971': '05061',
 '71972': '05113',
 '71973': '05113',
 '71998': '05019',
 '71999': '05019',
 '72001': '05105',
 '72002': '05125',
 '72003': '05001',
 '72004': '05069',
 '72005': '05067',
 '72006': '05147',
 '72007': '05085',
 '72010': '05145',
 '72011': '05125',
 '72012': '05145',
 '72013': '05141',
 '72014': '05067',
 '72015': '05125',
 '72016': '05105',
 '72017': '05117',
 '72019': '05125',
 '72020': '05067',
 '72021': '05095',
 '72022': '05125',
 '72023': '05085',
 '72024': '05085',
 '72025': '05105',
 '72026': '05001',
 '72027': '05029',
 '72028': '05141',
 '72029': '05095',
 '72030': '05029',
 '72031': '05141',
 '72032': '05045',
 '72034': '05045',
 '72035': '05045',
 '72036': '05147',
 '72038': '05001',
 '72039': '05045',
 '72040': '05117',
 '72041': '05117',
 '72042': '05001',
 '72044': '05023',
 '72045': '05145',
 '72046': '05085',
 '72047': '05045',
 '72048': '05001',
 '72051': '05137',
 '72052': '05145',
 '72053': '05119',
 '72055': '05001',
 '72057': '05053',
 '72058': '05045',
 '72059': '05147',
 '72060': '05145',
 '72061': '05045',
 '72063': '05029',
 '72064': '05117',
 '72065': '05125',
 '72066': '05117',
 '72067': '05023',
 '72068': '05145',
 '72069': '05095',
 '72070': '05105',
 '72072': '05085',
 '72073': '05001',
 '72074': '05147',
 '72075': '05067',
 '72076': '05119',
 '72079': '05069',
 '72080': '05141',
 '72081': '05145',
 '72082': '05145',
 '72083': '05085',
 '72084': '05039',
 '72085': '05145',
 '72086': '05085',
 '72087': '05125',
 '72088': '05141',
 '72099': '05119',
 '72101': '05147',
 '72102': '05145',
 '72103': '05125',
 '72104': '05059',
 '72106': '05045',
 '72107': '05029',
 '72108': '05095',
 '72110': '05029',
 '72111': '05045',
 '72112': '05067',
 '72113': '05119',
 '72114': '05119',
 '72116': '05119',
 '72117': '05119',
 '72118': '05119',
 '72119': '05119',
 '72120': '05119',
 '72121': '05145',
 '72122': '05125',
 '72123': '05147',
 '72125': '05105',
 '72126': '05105',
 '72127': '05029',
 '72128': '05053',
 '72129': '05053',
 '72130': '05023',
 '72131': '05023',
 '72132': '05069',
 '72133': '05069',
 '72134': '05095',
 '72135': '05119',
 '72136': '05145',
 '72137': '05145',
 '72139': '05145',
 '72140': '05001',
 '72141': '05141',
 '72142': '05085',
 '72143': '05145',
 '72150': '05053',
 '72152': '05069',
 '72153': '05141',
 '72156': '05029',
 '72157': '05029',
 '72160': '05001',
 '72165': '05063',
 '72166': '05001',
 '72167': '05125',
 '72168': '05069',
 '72169': '05067',
 '72170': '05117',
 '72173': '05045',
 '72175': '05069',
 '72176': '05085',
 '72178': '05145',
 '72179': '05023',
 '72180': '05119',
 '72181': '05045',
 '72182': '05069',
 '72183': '05119',
 '72199': '05119',
 '72201': '05119',
 '72202': '05119',
 '72204': '05119',
 '72205': '05119',
 '72206': '05119',
 '72207': '05119',
 '72209': '05119',
 '72210': '05119',
 '72211': '05119',
 '72212': '05119',
 '72223': '05119',
 '72227': '05119',
 '72301': '05035',
 '72311': '05077',
 '72313': '05093',
 '72315': '05093',
 '72320': '05077',
 '72322': '05123',
 '72324': '05037',
 '72325': '05035',
 '72326': '05123',
 '72327': '05035',
 '72328': '05041',
 '72329': '05093',
 '72330': '05093',
 '72331': '05035',
 '72332': '05035',
 '72333': '05107',
 '72335': '05123',
 '72338': '47167',
 '72339': '05035',
 '72340': '05123',
 '72341': '05077',
 '72342': '05107',
 '72346': '05123',
 '72347': '05037',
 '72348': '05035',
 '72350': '05093',
 '72351': '05093',
 '72352': '05077',
 '72353': '05107',
 '72354': '05111',
 '72355': '05107',
 '72358': '05093',
 '72359': '05123',
 '72360': '05077',
 '72364': '05035',
 '72365': '05111',
 '72366': '05107',
 '72367': '05107',
 '72368': '05077',
 '72369': '05107',
 '72370': '05093',
 '72372': '05123',
 '72373': '05037',
 '72374': '05107',
 '72376': '05035',
 '72377': '05111',
 '72379': '05041',
 '72383': '05107',
 '72384': '05035',
 '72386': '05111',
 '72387': '05037',
 '72389': '05107',
 '72390': '05107',
 '72391': '05093',
 '72392': '05123',
 '72394': '05123',
 '72395': '05093',
 '72396': '05037',
 '72401': '05031',
 '72404': '05031',
 '72405': '05031',
 '72410': '05075',
 '72411': '05031',
 '72412': '05055',
 '72413': '05121',
 '72414': '05031',
 '72415': '05075',
 '72416': '05031',
 '72417': '05031',
 '72419': '05031',
 '72421': '05031',
 '72422': '05021',
 '72424': '05021',
 '72425': '05055',
 '72426': '05093',
 '72427': '05031',
 '72428': '05093',
 '72429': '05111',
 '72430': '05021',
 '72431': '05067',
 '72432': '05111',
 '72433': '05075',
 '72434': '05121',
 '72435': '05021',
 '72436': '05055',
 '72437': '05031',
 '72438': '05093',
 '72440': '05075',
 '72441': '05021',
 '72442': '05093',
 '72443': '05055',
 '72444': '05121',
 '72445': '05075',
 '72447': '05031',
 '72449': '05121',
 '72450': '05055',
 '72453': '05021',
 '72454': '05021',
 '72455': '05121',
 '72456': '05021',
 '72457': '05075',
 '72458': '05075',
 '72459': '05121',
 '72460': '05121',
 '72461': '05021',
 '72462': '05121',
 '72464': '05021',
 '72466': '05075',
 '72467': '05031',
 '72469': '05075',
 '72470': '05021',
 '72471': '05067',
 '72472': '05111',
 '72473': '05067',
 '72476': '05075',
 '72478': '05121',
 '72479': '05111',
 '72482': '05135',
 '72501': '05063',
 '72512': '05065',
 '72513': '05135',
 '72515': '05049',
 '72517': '05065',
 '72519': '05005',
 '72520': '05049',
 '72521': '05135',
 '72522': '05063',
 '72523': '05023',
 '72524': '05063',
 '72526': '05063',
 '72527': '05063',
 '72528': '05065',
 '72529': '05135',
 '72530': '05023',
 '72531': '05049',
 '72532': '05135',
 '72533': '05137',
 '72534': '05063',
 '72536': '05065',
 '72537': '05005',
 '72538': '05049',
 '72539': '05049',
 '72540': '05065',
 '72542': '05135',
 '72543': '05023',
 '72544': '05005',
 '72546': '05023',
 '72550': '05063',
 '72553': '05063',
 '72554': '05049',
 '72555': '05137',
 '72556': '05065',
 '72560': '05137',
 '72561': '05065',
 '72562': '05063',
 '72564': '05063',
 '72565': '05065',
 '72566': '05065',
 '72567': '05137',
 '72568': '05063',
 '72569': '05135',
 '72571': '05063',
 '72572': '05075',
 '72573': '05065',
 '72576': '05049',
 '72577': '05065',
 '72578': '05049',
 '72579': '05063',
 '72581': '05023',
 '72583': '05049',
 '72584': '05065',
 '72585': '05065',
 '72587': '05065',
 '72601': '05009',
 '72611': '05015',
 '72615': '05009',
 '72616': '05015',
 '72617': '05005',
 '72619': '05089',
 '72623': '05005',
 '72624': '05101',
 '72626': '05005',
 '72628': '05101',
 '72629': '05141',
 '72630': '05009',
 '72631': '05015',
 '72632': '05015',
 '72633': '05089',
 '72634': '05089',
 '72635': '05005',
 '72636': '05129',
 '72638': '05015',
 '72639': '05129',
 '72640': '05101',
 '72641': '05101',
 '72642': '05005',
 '72644': '05009',
 '72645': '05129',
 '72648': '05101',
 '72650': '05129',
 '72651': '05005',
 '72653': '05005',
 '72655': '05101',
 '72658': '05005',
 '72660': '05015',
 '72661': '05089',
 '72662': '05009',
 '72663': '05137',
 '72666': '05101',
 '72668': '05089',
 '72669': '05129',
 '72670': '05101',
 '72672': '05089',
 '72675': '05129',
 '72677': '05089',
 '72679': '05129',
 '72680': '05137',
 '72682': '05089',
 '72683': '05101',
 '72685': '05101',
 '72686': '05115',
 '72687': '05089',
 '72701': '05143',
 '72703': '05143',
 '72704': '05143',
 '72712': '05007',
 '72713': '05007',
 '72714': '05007',
 '72715': '05007',
 '72717': '05143',
 '72718': '05007',
 '72719': '05007',
 '72721': '05087',
 '72722': '05007',
 '72727': '05087',
 '72729': '05143',
 '72730': '05143',
 '72732': '05007',
 '72734': '05007',
 '72736': '05007',
 '72738': '05087',
 '72739': '05007',
 '72740': '05087',
 '72742': '05087',
 '72744': '05143',
 '72745': '05007',
 '72747': '05007',
 '72749': '05143',
 '72751': '05007',
 '72752': '05087',
 '72753': '05143',
 '72756': '05007',
 '72758': '05007',
 '72760': '05087',
 '72761': '05007',
 '72762': '05143',
 '72764': '05143',
 '72768': '05007',
 '72769': '05143',
 '72773': '05087',
 '72774': '05143',
 '72776': '05087',
 '72801': '05115',
 '72802': '05115',
 '72821': '05047',
 '72823': '05115',
 '72824': '05149',
 '72826': '05083',
 '72827': '05149',
 '72828': '05149',
 '72829': '05149',
 '72830': '05071',
 '72832': '05071',
 '72833': '05149',
 '72834': '05149',
 '72835': '05083',
 '72837': '05115',
 '72838': '05149',
 '72839': '05071',
 '72840': '05071',
 '72841': '05127',
 '72842': '05149',
 '72843': '05115',
 '72845': '05071',
 '72846': '05071',
 '72847': '05115',
 '72851': '05083',
 '72852': '05071',
 '72853': '05149',
 '72854': '05071',
 '72855': '05083',
 '72856': '05101',
 '72857': '05149',
 '72858': '05115',
 '72860': '05149',
 '72863': '05083',
 '72865': '05083',
 '72901': '05131',
 '72903': '05131',
 '72904': '05131',
 '72905': '05131',
 '72908': '05131',
 '72916': '05131',
 '72921': '05033',
 '72923': '05131',
 '72926': '05127',
 '72927': '05083',
 '72928': '05047',
 '72930': '05047',
 '72932': '05033',
 '72933': '05047',
 '72934': '05033',
 '72935': '05033',
 '72936': '05131',
 '72937': '05131',
 '72938': '05131',
 '72940': '05131',
 '72941': '05131',
 '72943': '05083',
 '72944': '05131',
 '72945': '05131',
 '72946': '05033',
 '72947': '05047',
 '72948': '05033',
 '72949': '05047',
 '72950': '05127',
 '72951': '05083',
 '72952': '05033',
 '72955': '05033',
 '72956': '05033',
 '72958': '05127',
 '72959': '05143'}

In [56]:
new_dataset_df['county_FIPS'] = new_dataset_df['Zip'].map(c_FIPS_dict)

In [57]:
#Save the resulting dataframe to a csv
new_dataset_df.to_csv(os.path.join(state_dir,'cleaned.csv'), index=False)

In [58]:
new_dataset_df

,State,Zip,Utility,Population Served,Contaminant_Factor,county_FIPS
0,AR,71601,Arkansas Department of Corrections - Cummins U...,3800,379,05069
1,AR,71601,Arsenal Water,2577,255,05069
2,AR,71601,Garrett Bridge Water Association,784,75,05069
3,AR,71601,Gould Municipal,908,28,05069
4,AR,71601,Grady Waterworks,424,152,05069
...,...,...,...,...,...,...
92,AR,72826,Blue Mountain,357,1143,05083
93,AR,72826,Subiaco City,535,1263,05083
94,AR,72901,Franklin-Sebatian Public Water Authority,0,1013,05131
95,AR,72901,James Fork Regional Water District,11538,1311,05131
96,AR,72901,Milltown-washburn,3807,1163,05131