# Web Scraping of EWG Tap Water Database website to obtain water quality

In [1]:
import requests
import pandas as pd

In [2]:
url = requests.get('https://www.ewg.org/tapwater/state.php?stab=OR')
table = pd.read_html(url.text)

In [3]:
large_utilities_with_violations = table[1]
large_utilities_with_violations

,Utility,Location,PeopleServed,ViolationPoints
0,Trollers Cove Water Association,"Tidewater, OR",32,101
1,London Water Co-op,"Cottage Grove, OR",63,78
2,Manzanita Hills Subdivision,"Shady Cove, OR",27,65
3,"Richland, City of","Richland, OR",245,55
4,Weiss Estates Water System,"Bandon, OR",36,49
5,Skyview Acres Water Company,"Sandy, OR",200,47
6,Midland Water Association,"Clatskanie, OR",160,41
7,Dexter Oaks Co-op,"Dexter, OR",75,35
8,"Adrian, City of","Adrian, OR",180,34
9,"Monroe, City of","Monroe, OR",615,32
10,Swisshome Village,"Swisshome, OR",36,26
11,Youngs River Lewis & Clark Water District,"Astoria, OR",2530,25
12,Bolder City Water System,"Jacksonville, OR",60,21
13,"Sumpter, City of","Sumpter, OR",205,20
14,Mcnulty Water People's Utility District,"St. Helens, OR",2500,18
15,"Monument, City of","Monument, OR",130,15
16,Laurelwood Water Users,"Gaston, OR",200,13
17,Tooley Water District,"Newberg, OR",42,12
18,Elderberry Nehalem Ws,"Seaside, OR",140,12
19,Paradise/rogue Meadows Ws,"Clackamas, OR",165,11
20,Caseys Riverside Park,"Westfir, OR",84,11
21,Sunset Lake Rv Park,"Redmond, OR",170,10
22,Glide Water Association,"Glide, OR",1200,10
23,Hawks Point,"Eugene, OR",75,10
24,Shorewood Estates,"Albany, OR",148,10
25,Raintree Estates,"Corvallis, OR",50,10
26,Young Life,"Antelope, OR",482,10
27,Mount Terrace Mobile Home Park,"Culver City, OR",60,10
28,Brewster Community Homeowners,"Salem, OR",50,10
29,Country Club Estates Water District,"Coos Bay, OR",45,10

In [4]:
url = requests.get("https://www.ewg.org/tapwater/state.php?stab=AL")
table = pd.read_html(url.text)
table[1]

,Utility,Location,PeopleServed,ViolationPoints
0,Dekalb-Jackson Water Supply District,"Ider, AL",15531,30
1,North Clarke Water Authority,"Thomasville, AL",975,25
2,Cwm Water Authority,"Dickinson, AL",1722,10
3,Centre Water & Sewer Board,"Centre, AL",7050,5
4,Mid-central Water Authority,"Fulton, AL",2331,5
5,Thomasville Water Works & Sewer Board,"Thomasville, AL",6897,5
6,Union Grove Utility Board,"Union Grove, AL",2862,2
7,Prichard Water Works Board,"Prichard, AL",32400,2
8,Enterprise Water Works,"Enterprise, AL",48000,2
9,Mcintosh Water & Fire Pro Authority,"Mcintosh, AL",3060,1
10,Lemoyne Water System Inc.,"Axis, AL",3825,1
11,Saraland Water Service,"Saraland, AL",13827,1
12,Wadley Utilities Board,"Wadley, AL",873,1
13,Camp Hill Utilities Board,"Camp Hill, AL",1710,1
14,"Daviston Water System, Town of","Daviston, AL",630,1
15,Jasper Water Works and Sewer Board,"Jasper, AL",28638,1
16,Oneonta Utilities Board,"Oneonta, AL",19737,1
17,South Marengo Co. Water & Fire Pro Authority,"Linden, AL",5610,1
18,Hamden Ridge Water Authority,"Evergreen, AL",2196,1
19,Clay County Water Authority,"Lineville, AL",1818,1
20,Blount County Water,"Cleveland, AL",17400,1
21,Gantt Water System,"Gantt, AL",825,1
22,Winfield Water Works & Sewer Board,"Winfield, AL",8631,1
23,Harvest-Monrovia Water System,"Prospect, AL",51912,1
24,Beauregard Water Authority,"Opelika, AL",11178,1
25,Chisholm Heights Water & F P Authority,"Florence, AL",4500,1
26,Detroit Water Works,"Detroit, AL",435,1
27,Leeds Water Board,"Leeds, AL",21300,1
28,Gordon Town Of,"Gordon, AL",414,1
29,Dothan Utilities,"Dothan, AL",93459,1

In [5]:
table[1].columns

Index(['Utility', 'Location', 'PeopleServed', 'ViolationPoints'], dtype='object')

In [6]:
column_names = ['Utility', 'Location', 'PeopleServed', 'ViolationPoints']

violations_master_df = pd.DataFrame(columns = column_names)

In [7]:
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

In [8]:

for state in states:
    page="https://www.ewg.org/tapwater/state.php?stab=" + str(state)
    print(page)

https://www.ewg.org/tapwater/state.php?stab=AL
https://www.ewg.org/tapwater/state.php?stab=AK
https://www.ewg.org/tapwater/state.php?stab=AZ
https://www.ewg.org/tapwater/state.php?stab=AR
https://www.ewg.org/tapwater/state.php?stab=CA
https://www.ewg.org/tapwater/state.php?stab=CO
https://www.ewg.org/tapwater/state.php?stab=CT
https://www.ewg.org/tapwater/state.php?stab=DC
https://www.ewg.org/tapwater/state.php?stab=DE
https://www.ewg.org/tapwater/state.php?stab=FL
https://www.ewg.org/tapwater/state.php?stab=GA
https://www.ewg.org/tapwater/state.php?stab=HI
https://www.ewg.org/tapwater/state.php?stab=ID
https://www.ewg.org/tapwater/state.php?stab=IL
https://www.ewg.org/tapwater/state.php?stab=IN
https://www.ewg.org/tapwater/state.php?stab=IA
https://www.ewg.org/tapwater/state.php?stab=KS
https://www.ewg.org/tapwater/state.php?stab=KY
https://www.ewg.org/tapwater/state.php?stab=LA
https://www.ewg.org/tapwater/state.php?stab=ME
https://www.ewg.org/tapwater/state.php?stab=MD
https://www.ewg.org/tapwater/state.php?stab=MA
https://www.ewg.org/tapwater/state.php?stab=MI
https://www.ewg.org/tapwater/state.php?stab=MN
https://www.ewg.org/tapwater/state.php?stab=MS
https://www.ewg.org/tapwater/state.php?stab=MO
https://www.ewg.org/tapwater/state.php?stab=MT
https://www.ewg.org/tapwater/state.php?stab=NE
https://www.ewg.org/tapwater/state.php?stab=NV
https://www.ewg.org/tapwater/state.php?stab=NH
https://www.ewg.org/tapwater/state.php?stab=NJ
https://www.ewg.org/tapwater/state.php?stab=NM
https://www.ewg.org/tapwater/state.php?stab=NY
https://www.ewg.org/tapwater/state.php?stab=NC
https://www.ewg.org/tapwater/state.php?stab=ND
https://www.ewg.org/tapwater/state.php?stab=OH
https://www.ewg.org/tapwater/state.php?stab=OK
https://www.ewg.org/tapwater/state.php?stab=OR
https://www.ewg.org/tapwater/state.php?stab=PA
https://www.ewg.org/tapwater/state.php?stab=RI
https://www.ewg.org/tapwater/state.php?stab=SC
https://www.ewg.org/tapwater/state.php?stab=SD
https://www.ewg.org/tapwater/state.php?stab=TN
https://www.ewg.org/tapwater/state.php?stab=TX
https://www.ewg.org/tapwater/state.php?stab=UT
https://www.ewg.org/tapwater/state.php?stab=VT
https://www.ewg.org/tapwater/state.php?stab=VA
https://www.ewg.org/tapwater/state.php?stab=WA
https://www.ewg.org/tapwater/state.php?stab=WV
https://www.ewg.org/tapwater/state.php?stab=WI
https://www.ewg.org/tapwater/state.php?stab=WY

In [9]:
master_df = pd.DataFrame()
for state in states:
    page="https://www.ewg.org/tapwater/state.php?stab=" + str(state)
    url = requests.get(page)
    table = pd.read_html(url.text)
    master_df = master_df.append(table[1],ignore_index=True)
    #input("Press Enter to continue...")

In [10]:
master_df

,Utility,Location,PeopleServed,ViolationPoints
0,Dekalb-Jackson Water Supply District,"Ider, AL",15531,30
1,North Clarke Water Authority,"Thomasville, AL",975,25
2,Cwm Water Authority,"Dickinson, AL",1722,10
3,Centre Water & Sewer Board,"Centre, AL",7050,5
4,Mid-central Water Authority,"Fulton, AL",2331,5
...,...,...,...,...
1424,"Wheatland, Town Of","Wheatland, WY",3627,5
1425,Turnerville Water and Sewer District,"Grover, WY",90,5
1426,Kennington Springs Pipeline,"Grover, WY",45,5
1427,"Jackson, Town Of","Jackson, WY",8000,4
1428,"Cokeville, Town Of","Cokeville, WY",535,4

In [12]:
master_df.to_csv('Resources/Data/EWG_violationpoints.csv', index=False)