In [19]:
import pandas as pd
import os

In [6]:
df = pd.read_csv('../Resources/Data/Cleaned_Data/master_contaminants.csv')

In [7]:
df

,Utility,Contaminant_Factor,Zip,county_FIPS
0,Brookside Water Works,1202,35005,1073.0
1,Graysville Water & Sewer Board,1160,35005,1073.0
2,Irondale Water System,167,35005,1073.0
3,Leeds Water Board,138,35005,1073.0
4,Mulga Water Works and Gas Department,1154,35005,1073.0
...,...,...,...,...
5603,Moorefield Municipal Water,1013,26755,54027.0
5604,Wardensville Town Of,343,26755,54027.0
5605,Franklin Municipality Of,237,26802,54071.0
5606,Pendleton Co. Psd(brandywine),3183,26802,54071.0
5607,Pendleton County Psd Riverton,97,26802,54071.0

In [9]:
zips_df = pd.read_csv('../Resources/Data/simplemaps_uszips_basicv1.80/uszips.csv')

In [12]:
zips_df.columns

Index(['zip', 'lat', 'lng', 'city', 'state_id', 'state_name', 'zcta',
       'parent_zcta', 'population', 'density', 'county_fips', 'county_name',
       'county_weights', 'county_names_all', 'county_fips_all', 'imprecise',
       'military', 'timezone'],
      dtype='object')

In [13]:
zips_cleaned_df = zips_df[['county_fips','county_fips_all','county_name','zip', 'lat', 'lng', 'city', 'state_id', 'state_name']]

In [14]:
zips_cleaned_df

,county_fips,county_fips_all,county_name,zip,lat,lng,city,state_id,state_name
0,72001,72001|72141,Adjuntas,601,18.18027,-66.75266,Adjuntas,PR,Puerto Rico
1,72003,72003,Aguada,602,18.36075,-67.17541,Aguada,PR,Puerto Rico
2,72005,72005|72099,Aguadilla,603,18.45744,-67.12225,Aguadilla,PR,Puerto Rico
3,72093,72093|72153|72121,Maricao,606,18.16585,-66.93716,Maricao,PR,Puerto Rico
4,72011,72011|72099|72083|72003,Añasco,610,18.29110,-67.12243,Anasco,PR,Puerto Rico
...,...,...,...,...,...,...,...,...,...
33783,2198,02198,Prince of Wales-Hyder,99923,55.98043,-130.03803,Hyder,AK,Alaska
33784,2198,02198,Prince of Wales-Hyder,99925,55.55398,-132.96276,Klawock,AK,Alaska
33785,2198,02198,Prince of Wales-Hyder,99926,55.12617,-131.48928,Metlakatla,AK,Alaska
33786,2198,02198,Prince of Wales-Hyder,99927,56.33305,-133.60044,Point Baker,AK,Alaska
33787,2275,02275,Wrangell,99929,56.36089,-132.00635,Wrangell,AK,Alaska

In [15]:
zips_cleaned_df.to_csv('../Resources/Data/Cleaned_Data/master_zips.csv', index=False)

In [16]:
zips_cleaned_df.columns

Index(['county_fips', 'county_fips_all', 'county_name', 'zip', 'lat', 'lng',
       'city', 'state_id', 'state_name'],
      dtype='object')

In [20]:
data_dir = os.path.join('..', 'Census_Data_EDA')
county_fips_dictionary={}
with open(os.path.join('..', 'Census_Data_EDA',"State_County_FIPS.txt")) as file:
    for line in file:
        (key,value) = line.strip().split("        ")
        county_fips_dictionary[int(key)] = value

    print(f"\ntext file to county_fips_dictionary complete\n")
    
    first_value = list(county_fips_dictionary.values())[0]
    first_key = list(county_fips_dictionary.keys())[0]

    print('First Value: ', first_value)
    print('First Key: ', first_key)

ValueError: not enough values to unpack (expected 2, got 1)