In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Resources/Data/user_scrape_data/WV/cleaned.csv')

In [3]:
df

,Utility,Contaminant_Factor,Zip,county_FIPS
0,Appalachian Teen Challenge Female Center,66,24701,NaN
1,Athens Town Of,664,24701,NaN
2,Bluewell Psd,1559,24701,NaN
3,Green Valley Glenwood Psd Bulltail,2278,24701,NaN
4,Pinnacle Water Association,38,24701,NaN
...,...,...,...,...
338,Moorefield Municipal Water,1013,26755,NaN
339,Wardensville Town Of,343,26755,NaN
340,Franklin Municipality Of,237,26802,NaN
341,Pendleton Co. Psd(brandywine),3183,26802,NaN
342,Pendleton County Psd Riverton,97,26802,NaN